### ISSUE TITLE
Read the cookie from a browser?

### ISSUE THREAD

**Issue by samalba** [gorilla/securecookie#12]
I'm trying to read a secure cookie from the browser (just signed, not encrypted). The Base64 algorithm looks different from the native atob function...

Anyone tried this before?

**Comment by dchest** [comment]
@samalba base64 uses URL-safe encoding. To turn if into the normal encoding, do this:

```javascript
var output = cookie.replace("-", "+").replace("_", "/");
```

**Comment by elithrar** [comment]
@samalba I'm going to close this one out as Dmitry answered it.
