### ISSUE TITLE
Invalid value %v

### ISSUE THREAD

**Issue by carbocation** [gorilla/securecookie#13]
It is possible to generate an error yielding the literal message "[securecookie: invalid value %v](https://github.com/gorilla/securecookie/blob/f0559d009e6943011cd1ba6eb16195cf5e0ed326/securecookie.go#L199)" where the %v is a string literal.

Is the intent of this message to send back the value of `parts`, or is the %v literal intended?

**Comment by kisielk** [comment]
Nope, that was definitely a mistake. Thanks for catching that.

**Comment by kisielk** [comment]
I decided not to return the value of `parts` since we don't return it in any of the other error messages

**Comment by carbocation** [comment]
Seems reasonable. I like that you chose to reuse ErrMacInvalid here, since it's an accurate statement about the error, and also something that can be used externally to reason about the errors.
