### ISSUE TITLE
subtle test failure on go1.3

### ISSUE THREAD

**Issue by kisielk** [gorilla/securecookie#32]
I updated .travis.yml to include go1.5 and when the tests ran again there was a test failure on go1.3:

https://travis-ci.org/gorilla/securecookie/jobs/76404291

@elithrar any idea what would cause this?

**Comment by elithrar** [comment]
Yep! Ran into this myself elsewhere. [`subtle.ConstantTimeCompare`](https://github.com/golang/go/blob/master/src/crypto/subtle/constant_time.go#L12-L14) did not check that the lengths of each slice were equal prior to 1.4 - https://github.com/golang/go/commit/446bfffcd6cfcaca141988a9d844aac61a704866

I'm actually to blame for this when I committed https://github.com/gorilla/securecookie/commit/d8773d3e667317064f921c6fc6d840871797afc7

Can fix it if we want to retain <= 1.3 compatibility.

**Comment by kisielk** [comment]
hm, nobody seems to have complained about it, but go 1.4 was less than a year ago so it feels a bit premature to drop support for 1.3 just yet.

**Comment by elithrar** [comment]
Reverted d8773d3.
