### ISSUE TITLE
Asymmetric cookie encryption

### ISSUE THREAD

**Issue by alankm** [gorilla/securecookie#48]
Is it possible to use asymmetric encryption keys with securecookie, so that cookies generated by one server can be decrypted by another?

**Comment by elithrar** [comment]
Can you describe your use-case further? What would you be storing in the
cookies? What is each “server” doing here? Can the servers not share
secrets?

It’s unlikely pubkey encryption will be added as it does not fit the
primarily browser-based use-case of cookies.

**Comment by alankm** [comment]
Sure. I'm developing a constellation of servers that are each microservices within a larger ecosystem. I had an idea for one such service to act as a Single Sign-On authentication server, and thought it would be useful if it could generate secure-cookies for end-users.

This cookie would be required by every server within the constellation, and would be proof that the user has a valid session. The other servers therefore need to be able to decrypt the cookie, but will never need to encrypt one. 

It is probably viable for the servers to share secrets, but it isn't inconceivable that this might eventually cause problems. In any case, it just seems like good practice to limit the sharing of critical encryption keys as best as possible, if they're unnecessary.

I imagine that each server in the constellation would exist on a subdomain of a larger domain, and therefore getting the cookies handled automatically by browsers will be trivial.

**Comment by kisielk** [comment]
It would take a pretty serious redesign of the package internals to enable this, so it will probably never be supported by securecookie in its current incarnation. Maybe for a v2 or other package.
