### ISSUE TITLE
valid semver tag for vgo

### ISSUE THREAD

**Issue by flibustenet** [gorilla/securecookie#49]
The current tag `v1.1` is not compatible with vgo. Can it be changed to `v1.1.0` ?
When securecookie has no dependencies, i believe it doesn't need a `go.mod` file (i'm not sure).
I think it will also help the next step to v2

The related issue at vgo:
https://github.com/golang/go/issues/23954

**Comment by elithrar** [comment]
I’ll add a new tag shortly—the existing tag can’t (should not) be removed.

**Comment by elithrar** [comment]
Tagged: https://github.com/gorilla/securecookie/releases/tag/v1.1.1

**Comment by flibustenet** [comment]
I can confirm that `vgo` is happy now ! thanks
