### ISSUE TITLE
securecookie: AES-CTR origin

### ISSUE THREAD

**Issue by hollowaykeanho** [gorilla/securecookie#50]
Hello,

Quick question about the encryption. Is there a discussed research (or tests) for using AES-CTR + SHA256 approach instead of AES-GCM? For evaluation purposes for development.

Thanks in adv.

**Comment by elithrar** [comment]
This library existed before Go had an AES-GCM implementation:
https://golang.org/doc/go1.2#minor_library_changes

**Comment by hollowaykeanho** [comment]
Noted. Thanks.
