### ISSUE TITLE
corresponding Java implementation

### ISSUE THREAD

**Issue by zhao1-1** [gorilla/securecookie#75]
Excuse me, Does this algorithm have a corresponding Java implementation?

There is a Go Projection encode cookie by using this algorithm, and now , I want decode the cookie in Java Projection.

I can not find a java lib about decoding cookie by using this algorithm.

Please Help Me~~~

**Comment by elithrar** [comment]
There is not a Java library for this. What use-case requires you to issue
cookies in Go but decode in Java?

**Comment by zhao1-1** [comment]
I'm very grateful for your replay.
I want migrate Go project to Java project, and keep unchanged in implementing logic.

What algorithm or protol is our framework based on?

**Comment by coreydaley** [comment]
Unfortunately there is no easy way to do this, you would have to reverse engineer the process by which the cookie is built using this library, which is outside the scope of this project.
