### ISSUE TITLE
“securecookie/fuzz/corpus/c63ae6dd4fc9f9dda66970e827d13f7c73fe841c-1”Why is this file reported by antivirus software?

### ISSUE THREAD

**Issue by AnkoGo123** [gorilla/securecookie#76]
**Describe the problem you're having**
> A clear and concise description of what the bug is.

…

**Versions**
> Go version: `go version`

> package version: run `git rev-parse HEAD` inside the repo

…

**"Show me the code!"**
> A minimal code snippet can be useful, otherwise we're left guessing!

> Hint: wrap it with backticks to format it

…

**Comment by vvvvv** [comment]
You should ask this question your antivirus software provider.
